version: 2

sources:
  - name: jaffle_shop
    database: dbt-tutorial
    schema: jaffle_shop
    tables:
      - name: customers
        columns:
          - name: id
            test:
              - unique
              - not_null
      - name: orders
        columns:
          - name: id
            test:
              - unique
              - not_null