version: 2

sources:
  - name: jaffle_shop
    database: dbt-tutorial
    schema: jaffle_shop
    tables:
      - name: customers
        columns:
          - name: id
            test:
              - unique
              - not_null
      - name: orders
        columns:
          - name: id
            test:
              - unique
              - not_null

  - name: analytics
    description: Information comming form analytics in the web site.
    database: bigquery-public-data
    schema: ga4_obfuscated_sample_ecommerce
    tables:
      - name: events
        identifier: events_20210104
        description: Continuous analytics stream comming from Google Analytics
        loaded_at_field: event_timestamp
